export const COLLEGES = [
  // ── MBA (India) ──────────────────────────────────────────────────────
  {
    id: 'iima', name: 'IIM Ahmedabad', shortName: 'IIM-A',
    category: 'MBA', country: 'India', degreeTypes: ['MBA'], city: 'Ahmedabad', state: 'Gujarat',
    totalFee: 2500000, avgPackage: 3400000, highestPackage: 8500000,
    minScore: 97, minGpa: 70, minExpYears: 0, maxExpYears: 10,
    ranking: 1, nirf: 1,
    testTypes: ['cat'], tags: ['Top Tier', 'Finance', 'Strategy', 'Consulting'],
    placementTime: '2 months', scholarship: true, emoji: '🏛️',
  },
  {
    id: 'iimb', name: 'IIM Bangalore', shortName: 'IIM-B',
    category: 'MBA', country: 'India', degreeTypes: ['MBA'], city: 'Bangalore', state: 'Karnataka',
    totalFee: 2300000, avgPackage: 3000000, highestPackage: 7200000,
    minScore: 96, minGpa: 68, minExpYears: 0, maxExpYears: 10,
    ranking: 2, nirf: 2,
    testTypes: ['cat'], tags: ['Top Tier', 'Entrepreneurship', 'Tech', 'Finance'],
    placementTime: '2 months', scholarship: true, emoji: '🏛️',
  },
  {
    id: 'iimc', name: 'IIM Calcutta', shortName: 'IIM-C',
    category: 'MBA', country: 'India', degreeTypes: ['MBA'], city: 'Kolkata', state: 'West Bengal',
    totalFee: 2200000, avgPackage: 2800000, highestPackage: 7000000,
    minScore: 95, minGpa: 67, minExpYears: 0, maxExpYears: 10,
    ranking: 3, nirf: 3,
    testTypes: ['cat'], tags: ['Top Tier', 'Finance', 'Operations'],
    placementTime: '2 months', scholarship: true, emoji: '🏛️',
  },
  {
    id: 'isb', name: 'ISB Hyderabad', shortName: 'ISB',
    category: 'MBA', country: 'India', degreeTypes: ['MBA'], city: 'Hyderabad', state: 'Telangana',
    totalFee: 4200000, avgPackage: 3400000, highestPackage: 9000000,
    minScore: 88, minGpa: 65, minExpYears: 2, maxExpYears: 15,
    ranking: 4, nirf: 5,
    testTypes: ['gmat', 'gre'], tags: ['Top Tier', 'Global', 'Finance', 'Consulting', 'Experience Required'],
    placementTime: '3 months', scholarship: true, emoji: '🎓',
  },
  {
    id: 'fms', name: 'FMS Delhi', shortName: 'FMS',
    category: 'MBA', country: 'India', degreeTypes: ['MBA'], city: 'Delhi', state: 'Delhi',
    totalFee: 200000, avgPackage: 2200000, highestPackage: 5500000,
    minScore: 96, minGpa: 65, minExpYears: 0, maxExpYears: 10,
    ranking: 5, nirf: 7,
    testTypes: ['cat'], tags: ['Best Value', 'Finance', 'Marketing'],
    placementTime: '2 months', scholarship: false, emoji: '🏫',
  },
  {
    id: 'xlri', name: 'XLRI Jamshedpur', shortName: 'XLRI',
    category: 'MBA', country: 'India', degreeTypes: ['MBA'], city: 'Jamshedpur', state: 'Jharkhand',
    totalFee: 2600000, avgPackage: 2600000, highestPackage: 6000000,
    minScore: 93, minGpa: 65, minExpYears: 0, maxExpYears: 10,
    ranking: 6, nirf: 10,
    testTypes: ['xat', 'gmat'], tags: ['HR Excellence', 'Business Management'],
    placementTime: '2 months', scholarship: true, emoji: '🏛️',
  },
  {
    id: 'spjimr', name: 'SPJIMR Mumbai', shortName: 'SPJIMR',
    category: 'MBA', country: 'India', degreeTypes: ['MBA'], city: 'Mumbai', state: 'Maharashtra',
    totalFee: 2000000, avgPackage: 2200000, highestPackage: 5500000,
    minScore: 90, minGpa: 63, minExpYears: 0, maxExpYears: 8,
    ranking: 7, nirf: 8,
    testTypes: ['cat', 'gmat'], tags: ['Mumbai', 'Marketing', 'Social Consciousness'],
    placementTime: '2 months', scholarship: true, emoji: '🏛️',
  },
  {
    id: 'mdi', name: 'MDI Gurgaon', shortName: 'MDI',
    category: 'MBA', country: 'India', degreeTypes: ['MBA'], city: 'Gurgaon', state: 'Haryana',
    totalFee: 1800000, avgPackage: 2000000, highestPackage: 4500000,
    minScore: 92, minGpa: 63, minExpYears: 0, maxExpYears: 8,
    ranking: 8, nirf: 11,
    testTypes: ['cat', 'gmat'], tags: ['NCR', 'Finance', 'Consulting'],
    placementTime: '2 months', scholarship: true, emoji: '🏛️',
  },
  {
    id: 'iiml', name: 'IIM Lucknow', shortName: 'IIM-L',
    category: 'MBA', country: 'India', degreeTypes: ['MBA'], city: 'Lucknow', state: 'Uttar Pradesh',
    totalFee: 2000000, avgPackage: 2400000, highestPackage: 5800000,
    minScore: 94, minGpa: 66, minExpYears: 0, maxExpYears: 10,
    ranking: 9, nirf: 6,
    testTypes: ['cat'], tags: ['Top Tier', 'Agri-Business', 'Finance'],
    placementTime: '2 months', scholarship: true, emoji: '🏛️',
  },
  {
    id: 'iimi', name: 'IIM Indore', shortName: 'IIM-I',
    category: 'MBA', country: 'India', degreeTypes: ['MBA'], city: 'Indore', state: 'Madhya Pradesh',
    totalFee: 1600000, avgPackage: 1700000, highestPackage: 4000000,
    minScore: 91, minGpa: 63, minExpYears: 0, maxExpYears: 8,
    ranking: 10, nirf: 9,
    testTypes: ['cat'], tags: ['Affordable IIM', 'Operations', 'Finance'],
    placementTime: '2 months', scholarship: true, emoji: '🏛️',
  },
  {
    id: 'nmims', name: 'NMIMS Mumbai', shortName: 'NMIMS',
    category: 'MBA', country: 'India', degreeTypes: ['MBA'], city: 'Mumbai', state: 'Maharashtra',
    totalFee: 1600000, avgPackage: 1600000, highestPackage: 3800000,
    minScore: 85, minGpa: 60, minExpYears: 0, maxExpYears: 8,
    ranking: 11, nirf: 14,
    testTypes: ['cat', 'gmat'], tags: ['Mumbai', 'Marketing', 'Finance'],
    placementTime: '3 months', scholarship: false, emoji: '🏫',
  },
  {
    id: 'sibm', name: 'Symbiosis Institute of Business Management, Pune', shortName: 'SIBM Pune',
    category: 'MBA', country: 'India', degreeTypes: ['MBA'], city: 'Pune', state: 'Maharashtra',
    totalFee: 1900000, avgPackage: 1400000, highestPackage: 3200000,
    minScore: 80, minGpa: 58, minExpYears: 0, maxExpYears: 8,
    ranking: 12, nirf: 15,
    testTypes: ['cat', 'gmat'], tags: ['Pune', 'HR', 'Marketing'],
    placementTime: '3 months', scholarship: false, emoji: '🏫',
  },
  {
    id: 'great-lakes', name: 'Great Lakes Institute of Management, Chennai', shortName: 'Great Lakes',
    category: 'MBA', country: 'India', degreeTypes: ['MBA'], city: 'Chennai', state: 'Tamil Nadu',
    totalFee: 1500000, avgPackage: 1300000, highestPackage: 3000000,
    minScore: 75, minGpa: 55, minExpYears: 0, maxExpYears: 8,
    ranking: 13, nirf: 18,
    testTypes: ['cat', 'gmat'], tags: ['Chennai', 'Analytics', 'Affordable'],
    placementTime: '3 months', scholarship: false, emoji: '🏫',
  },

  // ── ENGINEERING (India) ─────────────────────────────────────────────
  {
    id: 'iitb', name: 'IIT Bombay', shortName: 'IIT-B',
    category: 'Engineering', country: 'India', degreeTypes: ['BTech', 'MTech'], city: 'Mumbai', state: 'Maharashtra',
    totalFee: 800000, avgPackage: 3000000, highestPackage: 12000000,
    minScore: 99, minGpa: 75, minExpYears: 0, maxExpYears: 0,
    ranking: 1, nirf: 3,
    testTypes: ['jee'], tags: ['Top Tier', 'CS', 'AI/ML', 'Research'],
    placementTime: '3 months', scholarship: true, emoji: '⚙️',
  },
  {
    id: 'iitd', name: 'IIT Delhi', shortName: 'IIT-D',
    category: 'Engineering', country: 'India', degreeTypes: ['BTech', 'MTech'], city: 'Delhi', state: 'Delhi',
    totalFee: 800000, avgPackage: 2500000, highestPackage: 10000000,
    minScore: 98, minGpa: 73, minExpYears: 0, maxExpYears: 0,
    ranking: 2, nirf: 4,
    testTypes: ['jee'], tags: ['Top Tier', 'CS', 'Electronics', 'Research'],
    placementTime: '3 months', scholarship: true, emoji: '⚙️',
  },
  {
    id: 'iitm', name: 'IIT Madras', shortName: 'IIT-M',
    category: 'Engineering', country: 'India', degreeTypes: ['BTech', 'MTech'], city: 'Chennai', state: 'Tamil Nadu',
    totalFee: 800000, avgPackage: 2000000, highestPackage: 8000000,
    minScore: 97, minGpa: 72, minExpYears: 0, maxExpYears: 0,
    ranking: 3, nirf: 1,
    testTypes: ['jee'], tags: ['Top Tier', 'Deep Tech', 'Research', 'CS'],
    placementTime: '3 months', scholarship: true, emoji: '⚙️',
  },
  {
    id: 'iitk', name: 'IIT Kanpur', shortName: 'IIT-K',
    category: 'Engineering', country: 'India', degreeTypes: ['BTech', 'MTech'], city: 'Kanpur', state: 'Uttar Pradesh',
    totalFee: 800000, avgPackage: 2200000, highestPackage: 9000000,
    minScore: 97, minGpa: 72, minExpYears: 0, maxExpYears: 0,
    ranking: 4, nirf: 5,
    testTypes: ['jee', 'gate'], tags: ['Top Tier', 'Aerospace', 'CS', 'Research'],
    placementTime: '3 months', scholarship: true, emoji: '⚙️',
  },
  {
    id: 'iitkgp', name: 'IIT Kharagpur', shortName: 'IIT-KGP',
    category: 'Engineering', country: 'India', degreeTypes: ['BTech', 'MTech'], city: 'Kharagpur', state: 'West Bengal',
    totalFee: 800000, avgPackage: 2100000, highestPackage: 8500000,
    minScore: 96, minGpa: 71, minExpYears: 0, maxExpYears: 0,
    ranking: 5, nirf: 6,
    testTypes: ['jee', 'gate'], tags: ['Oldest IIT', 'Mining', 'CS', 'Research'],
    placementTime: '3 months', scholarship: true, emoji: '⚙️',
  },
  {
    id: 'dtu', name: 'Delhi Technological University', shortName: 'DTU',
    category: 'Engineering', country: 'India', degreeTypes: ['BTech', 'MTech'], city: 'Delhi', state: 'Delhi',
    totalFee: 600000, avgPackage: 1200000, highestPackage: 4500000,
    minScore: 85, minGpa: 65, minExpYears: 0, maxExpYears: 0,
    ranking: 6, nirf: 30,
    testTypes: ['jee'], tags: ['Best Value', 'CS', 'Delhi NCR'],
    placementTime: '3 months', scholarship: true, emoji: '⚙️',
  },
  {
    id: 'bits', name: 'BITS Pilani', shortName: 'BITS',
    category: 'Engineering', country: 'India', degreeTypes: ['BTech', 'MTech'], city: 'Pilani', state: 'Rajasthan',
    totalFee: 1800000, avgPackage: 1500000, highestPackage: 5000000,
    minScore: 90, minGpa: 68, minExpYears: 0, maxExpYears: 0,
    ranking: 7, nirf: 26,
    testTypes: ['bitsat', 'jee'], tags: ['Flexible Curriculum', 'CS', 'Dual Degree'],
    placementTime: '3 months', scholarship: true, emoji: '⚙️',
  },
  {
    id: 'vit', name: 'VIT Vellore', shortName: 'VIT',
    category: 'Engineering', country: 'India', degreeTypes: ['BTech', 'MTech'], city: 'Vellore', state: 'Tamil Nadu',
    totalFee: 700000, avgPackage: 800000, highestPackage: 3500000,
    minScore: 75, minGpa: 60, minExpYears: 0, maxExpYears: 0,
    ranking: 8, nirf: 11,
    testTypes: ['viteee', 'jee'], tags: ['Industry Connect', 'CS', 'Affordable'],
    placementTime: '4 months', scholarship: true, emoji: '⚙️',
  },
  {
    id: 'nit-trichy', name: 'NIT Trichy', shortName: 'NIT-T',
    category: 'Engineering', country: 'India', degreeTypes: ['BTech', 'MTech'], city: 'Tiruchirappalli', state: 'Tamil Nadu',
    totalFee: 500000, avgPackage: 1200000, highestPackage: 4500000,
    minScore: 88, minGpa: 65, minExpYears: 0, maxExpYears: 0,
    ranking: 9, nirf: 9,
    testTypes: ['jee'], tags: ['Best Value', 'Core Engineering', 'Infra'],
    placementTime: '3 months', scholarship: true, emoji: '⚙️',
  },

  // ── MEDICAL (India) ──────────────────────────────────────────────────
  {
    id: 'aiims-delhi', name: 'AIIMS New Delhi', shortName: 'AIIMS',
    category: 'Medical', country: 'India', degreeTypes: ['Other'], city: 'Delhi', state: 'Delhi',
    totalFee: 50000, avgPackage: 1000000, highestPackage: 2000000,
    minScore: 99, minGpa: 80, minExpYears: 0, maxExpYears: 0,
    ranking: 1, nirf: 1,
    testTypes: ['neet'], tags: ['Top Tier', 'Research', 'Subsidized'],
    placementTime: '12 months', scholarship: false, emoji: '⚕️',
  },
  {
    id: 'cmc', name: 'CMC Vellore', shortName: 'CMC',
    category: 'Medical', country: 'India', degreeTypes: ['Other'], city: 'Vellore', state: 'Tamil Nadu',
    totalFee: 500000, avgPackage: 900000, highestPackage: 1800000,
    minScore: 97, minGpa: 78, minExpYears: 0, maxExpYears: 0,
    ranking: 2, nirf: 3,
    testTypes: ['neet'], tags: ['Top Tier', 'Christian College', 'Clinical Excellence'],
    placementTime: '12 months', scholarship: true, emoji: '⚕️',
  },
  {
    id: 'kmc', name: 'Kasturba Medical College Manipal', shortName: 'KMC',
    category: 'Medical', country: 'India', degreeTypes: ['Other'], city: 'Manipal', state: 'Karnataka',
    totalFee: 5000000, avgPackage: 800000, highestPackage: 1500000,
    minScore: 82, minGpa: 70, minExpYears: 0, maxExpYears: 0,
    ranking: 3, nirf: 10,
    testTypes: ['neet'], tags: ['Private', 'International Exposure', 'Clinical'],
    placementTime: '12 months', scholarship: true, emoji: '⚕️',
  },
  {
    id: 'jipmer', name: 'JIPMER Puducherry', shortName: 'JIPMER',
    category: 'Medical', country: 'India', degreeTypes: ['Other'], city: 'Puducherry', state: 'Puducherry',
    totalFee: 60000, avgPackage: 950000, highestPackage: 1800000,
    minScore: 98, minGpa: 79, minExpYears: 0, maxExpYears: 0,
    ranking: 4, nirf: 4,
    testTypes: ['neet'], tags: ['Government', 'Best Value', 'Research'],
    placementTime: '12 months', scholarship: false, emoji: '⚕️',
  },
  {
    id: 'mamc', name: 'Maulana Azad Medical College, Delhi', shortName: 'MAMC',
    category: 'Medical', country: 'India', degreeTypes: ['Other'], city: 'Delhi', state: 'Delhi',
    totalFee: 70000, avgPackage: 900000, highestPackage: 1600000,
    minScore: 96, minGpa: 78, minExpYears: 0, maxExpYears: 0,
    ranking: 5, nirf: 12,
    testTypes: ['neet'], tags: ['Government', 'Delhi', 'Clinical Excellence'],
    placementTime: '12 months', scholarship: false, emoji: '⚕️',
  },

  // ── STUDY ABROAD — USA ───────────────────────────────────────────────
  {
    id: 'hbs', name: 'Harvard Business School', shortName: 'HBS',
    category: 'Study Abroad', country: 'USA', degreeTypes: ['MBA'], city: 'Boston', state: 'USA',
    totalFee: 12000000, avgPackage: 20000000, highestPackage: 50000000,
    minScore: 95, minGpa: 75, minExpYears: 3, maxExpYears: 15,
    ranking: 1, nirf: null,
    testTypes: ['gmat', 'gre'], tags: ['World #1', 'USA', 'Network', 'Consulting', 'Finance'],
    placementTime: '2 months', scholarship: true, emoji: '🇺🇸',
  },
  {
    id: 'wharton', name: 'Wharton School, UPenn', shortName: 'Wharton',
    category: 'Study Abroad', country: 'USA', degreeTypes: ['MBA'], city: 'Philadelphia', state: 'USA',
    totalFee: 11500000, avgPackage: 19000000, highestPackage: 48000000,
    minScore: 94, minGpa: 74, minExpYears: 3, maxExpYears: 15,
    ranking: 2, nirf: null,
    testTypes: ['gmat', 'gre'], tags: ['Finance', 'USA', 'Network'],
    placementTime: '2 months', scholarship: true, emoji: '🇺🇸',
  },
  {
    id: 'stanford-gsb', name: 'Stanford Graduate School of Business', shortName: 'Stanford GSB',
    category: 'Study Abroad', country: 'USA', degreeTypes: ['MBA'], city: 'Stanford', state: 'USA',
    totalFee: 12500000, avgPackage: 21000000, highestPackage: 55000000,
    minScore: 96, minGpa: 76, minExpYears: 3, maxExpYears: 15,
    ranking: 3, nirf: null,
    testTypes: ['gmat', 'gre'], tags: ['Entrepreneurship', 'USA', 'Tech'],
    placementTime: '2 months', scholarship: true, emoji: '🇺🇸',
  },
  {
    id: 'mit-sloan', name: 'MIT Sloan School of Management', shortName: 'MIT Sloan',
    category: 'Study Abroad', country: 'USA', degreeTypes: ['MBA'], city: 'Cambridge', state: 'USA',
    totalFee: 11800000, avgPackage: 19500000, highestPackage: 48000000,
    minScore: 93, minGpa: 74, minExpYears: 3, maxExpYears: 14,
    ranking: 4, nirf: null,
    testTypes: ['gmat', 'gre'], tags: ['Tech', 'Analytics', 'USA'],
    placementTime: '2 months', scholarship: true, emoji: '🇺🇸',
  },
  {
    id: 'mit-meng', name: 'MIT (MEng / MS Engineering)', shortName: 'MIT',
    category: 'Study Abroad', country: 'USA', degreeTypes: ['MS', 'MTech'], city: 'Cambridge', state: 'USA',
    totalFee: 7500000, avgPackage: 12000000, highestPackage: 25000000,
    minScore: 90, minGpa: 75, minExpYears: 0, maxExpYears: 6,
    ranking: 5, nirf: null,
    testTypes: ['gre', 'ielts'], tags: ['World #1 Engineering', 'AI/ML', 'USA'],
    placementTime: '3 months', scholarship: true, emoji: '🇺🇸',
  },
  {
    id: 'cmu-mscs', name: 'Carnegie Mellon University (MS CS)', shortName: 'CMU',
    category: 'Study Abroad', country: 'USA', degreeTypes: ['MS'], city: 'Pittsburgh', state: 'USA',
    totalFee: 7000000, avgPackage: 11500000, highestPackage: 24000000,
    minScore: 88, minGpa: 74, minExpYears: 0, maxExpYears: 6,
    ranking: 6, nirf: null,
    testTypes: ['gre', 'ielts'], tags: ['CS', 'AI/ML', 'USA'],
    placementTime: '3 months', scholarship: true, emoji: '🇺🇸',
  },

  // ── STUDY ABROAD — UK ────────────────────────────────────────────────
  {
    id: 'lbs', name: 'London Business School', shortName: 'LBS',
    category: 'Study Abroad', country: 'UK', degreeTypes: ['MBA'], city: 'London', state: 'UK',
    totalFee: 8000000, avgPackage: 16000000, highestPackage: 40000000,
    minScore: 90, minGpa: 72, minExpYears: 3, maxExpYears: 12,
    ranking: 1, nirf: null,
    testTypes: ['gmat', 'gre'], tags: ['World Top 10', 'UK', 'Finance', 'Europe Access'],
    placementTime: '2 months', scholarship: true, emoji: '🇬🇧',
  },
  {
    id: 'oxford-said', name: 'Oxford Saïd Business School', shortName: 'Oxford Saïd',
    category: 'Study Abroad', country: 'UK', degreeTypes: ['MBA'], city: 'Oxford', state: 'UK',
    totalFee: 7500000, avgPackage: 14500000, highestPackage: 35000000,
    minScore: 88, minGpa: 72, minExpYears: 2, maxExpYears: 12,
    ranking: 2, nirf: null,
    testTypes: ['gmat', 'gre'], tags: ['Brand Prestige', 'UK', 'Global Network'],
    placementTime: '2 months', scholarship: true, emoji: '🇬🇧',
  },
  {
    id: 'cambridge-judge', name: 'Cambridge Judge Business School', shortName: 'Cambridge Judge',
    category: 'Study Abroad', country: 'UK', degreeTypes: ['MBA'], city: 'Cambridge', state: 'UK',
    totalFee: 7300000, avgPackage: 14000000, highestPackage: 33000000,
    minScore: 87, minGpa: 71, minExpYears: 2, maxExpYears: 12,
    ranking: 3, nirf: null,
    testTypes: ['gmat', 'gre'], tags: ['Entrepreneurship', 'UK', 'Tech'],
    placementTime: '2 months', scholarship: true, emoji: '🇬🇧',
  },
  {
    id: 'imperial', name: 'Imperial College Business School', shortName: 'Imperial',
    category: 'Study Abroad', country: 'UK', degreeTypes: ['MBA', 'MS'], city: 'London', state: 'UK',
    totalFee: 6500000, avgPackage: 12500000, highestPackage: 30000000,
    minScore: 82, minGpa: 68, minExpYears: 0, maxExpYears: 10,
    ranking: 4, nirf: null,
    testTypes: ['gmat', 'gre', 'ielts'], tags: ['Finance', 'Tech', 'London'],
    placementTime: '3 months', scholarship: true, emoji: '🇬🇧',
  },
  {
    id: 'ucl', name: 'University College London (MS)', shortName: 'UCL',
    category: 'Study Abroad', country: 'UK', degreeTypes: ['MS'], city: 'London', state: 'UK',
    totalFee: 4500000, avgPackage: 9000000, highestPackage: 20000000,
    minScore: 75, minGpa: 65, minExpYears: 0, maxExpYears: 8,
    ranking: 5, nirf: null,
    testTypes: ['gre', 'ielts'], tags: ['London', 'Research', 'Affordable Global'],
    placementTime: '3 months', scholarship: true, emoji: '🇬🇧',
  },

  // ── STUDY ABROAD — CANADA ────────────────────────────────────────────
  {
    id: 'utoronto', name: 'University of Toronto (Rotman)', shortName: 'UofT',
    category: 'Study Abroad', country: 'Canada', degreeTypes: ['MBA'], city: 'Toronto', state: 'Canada',
    totalFee: 4000000, avgPackage: 8000000, highestPackage: 18000000,
    minScore: 82, minGpa: 70, minExpYears: 2, maxExpYears: 12,
    ranking: 1, nirf: null,
    testTypes: ['gmat', 'gre'], tags: ['Canada', 'PR Pathway', 'Affordable Global'],
    placementTime: '3 months', scholarship: true, emoji: '🇨🇦',
  },
  {
    id: 'ivey', name: 'Ivey Business School, Western University', shortName: 'Ivey',
    category: 'Study Abroad', country: 'Canada', degreeTypes: ['MBA'], city: 'London (Ontario)', state: 'Canada',
    totalFee: 3700000, avgPackage: 7200000, highestPackage: 16000000,
    minScore: 78, minGpa: 68, minExpYears: 2, maxExpYears: 12,
    ranking: 2, nirf: null,
    testTypes: ['gmat', 'gre'], tags: ['Case Method', 'Canada', 'PR Pathway'],
    placementTime: '3 months', scholarship: true, emoji: '🇨🇦',
  },
  {
    id: 'ubc-sauder', name: 'UBC Sauder School of Business', shortName: 'UBC Sauder',
    category: 'Study Abroad', country: 'Canada', degreeTypes: ['MBA', 'MS'], city: 'Vancouver', state: 'Canada',
    totalFee: 3500000, avgPackage: 6800000, highestPackage: 15000000,
    minScore: 75, minGpa: 66, minExpYears: 0, maxExpYears: 10,
    ranking: 3, nirf: null,
    testTypes: ['gmat', 'gre', 'ielts'], tags: ['Canada', 'PR Pathway', 'Tech'],
    placementTime: '3 months', scholarship: true, emoji: '🇨🇦',
  },
  {
    id: 'mcgill-desautels', name: 'McGill University (Desautels)', shortName: 'McGill',
    category: 'Study Abroad', country: 'Canada', degreeTypes: ['MBA'], city: 'Montreal', state: 'Canada',
    totalFee: 3200000, avgPackage: 6500000, highestPackage: 14000000,
    minScore: 74, minGpa: 65, minExpYears: 2, maxExpYears: 10,
    ranking: 4, nirf: null,
    testTypes: ['gmat', 'gre'], tags: ['Canada', 'Bilingual', 'PR Pathway'],
    placementTime: '3 months', scholarship: true, emoji: '🇨🇦',
  },

  // ── STUDY ABROAD — AUSTRALIA ─────────────────────────────────────────
  {
    id: 'umelbourne', name: 'University of Melbourne', shortName: 'UMelb',
    category: 'Study Abroad', country: 'Australia', degreeTypes: ['MBA', 'MS'], city: 'Melbourne', state: 'Australia',
    totalFee: 3500000, avgPackage: 7000000, highestPackage: 15000000,
    minScore: 78, minGpa: 65, minExpYears: 0, maxExpYears: 10,
    ranking: 1, nirf: null,
    testTypes: ['gmat', 'gre', 'ielts'], tags: ['Australia', 'PR Pathway', 'Quality of Life'],
    placementTime: '3 months', scholarship: true, emoji: '🇦🇺',
  },
  {
    id: 'unsw', name: 'UNSW Sydney Business School', shortName: 'UNSW',
    category: 'Study Abroad', country: 'Australia', degreeTypes: ['MBA', 'MS'], city: 'Sydney', state: 'Australia',
    totalFee: 3200000, avgPackage: 6500000, highestPackage: 14000000,
    minScore: 72, minGpa: 62, minExpYears: 0, maxExpYears: 10,
    ranking: 2, nirf: null,
    testTypes: ['gmat', 'gre', 'ielts'], tags: ['Australia', 'PR Pathway', 'Fintech'],
    placementTime: '3 months', scholarship: true, emoji: '🇦🇺',
  },
  {
    id: 'usydney', name: 'University of Sydney Business School', shortName: 'USyd',
    category: 'Study Abroad', country: 'Australia', degreeTypes: ['MBA', 'MS'], city: 'Sydney', state: 'Australia',
    totalFee: 3300000, avgPackage: 6600000, highestPackage: 14500000,
    minScore: 72, minGpa: 62, minExpYears: 0, maxExpYears: 10,
    ranking: 3, nirf: null,
    testTypes: ['gmat', 'gre', 'ielts'], tags: ['Australia', 'PR Pathway', 'Research'],
    placementTime: '3 months', scholarship: true, emoji: '🇦🇺',
  },

  // ── STUDY ABROAD — GERMANY ───────────────────────────────────────────
  {
    id: 'tum', name: 'TU Munich', shortName: 'TUM',
    category: 'Study Abroad', country: 'Germany', degreeTypes: ['MS', 'MTech'], city: 'Munich', state: 'Germany',
    totalFee: 500000, avgPackage: 6000000, highestPackage: 12000000,
    minScore: 75, minGpa: 65, minExpYears: 0, maxExpYears: 8,
    ranking: 1, nirf: null,
    testTypes: ['gre', 'ielts'], tags: ['Germany', 'Almost Free', 'Engineering', 'Tech'],
    placementTime: '4 months', scholarship: true, emoji: '🇩🇪',
  },
  {
    id: 'mannheim', name: 'Mannheim Business School', shortName: 'Mannheim',
    category: 'Study Abroad', country: 'Germany', degreeTypes: ['MBA'], city: 'Mannheim', state: 'Germany',
    totalFee: 4500000, avgPackage: 8500000, highestPackage: 18000000,
    minScore: 70, minGpa: 62, minExpYears: 2, maxExpYears: 12,
    ranking: 2, nirf: null,
    testTypes: ['gmat', 'gre'], tags: ['Germany', 'Europe Access', 'Finance'],
    placementTime: '3 months', scholarship: true, emoji: '🇩🇪',
  },
  {
    id: 'rwth-aachen', name: 'RWTH Aachen University', shortName: 'RWTH Aachen',
    category: 'Study Abroad', country: 'Germany', degreeTypes: ['MS', 'MTech'], city: 'Aachen', state: 'Germany',
    totalFee: 450000, avgPackage: 5500000, highestPackage: 11000000,
    minScore: 70, minGpa: 62, minExpYears: 0, maxExpYears: 8,
    ranking: 3, nirf: null,
    testTypes: ['gre', 'ielts'], tags: ['Germany', 'Almost Free', 'Mechanical', 'Engineering'],
    placementTime: '4 months', scholarship: true, emoji: '🇩🇪',
  },

  // ── STUDY ABROAD — IRELAND ───────────────────────────────────────────
  {
    id: 'tcd', name: 'Trinity College Dublin', shortName: 'TCD',
    category: 'Study Abroad', country: 'Ireland', degreeTypes: ['MBA', 'MS'], city: 'Dublin', state: 'Ireland',
    totalFee: 3000000, avgPackage: 6500000, highestPackage: 14000000,
    minScore: 74, minGpa: 63, minExpYears: 0, maxExpYears: 8,
    ranking: 1, nirf: null,
    testTypes: ['gmat', 'gre', 'ielts'], tags: ['Ireland', 'EU Access', 'English Speaking'],
    placementTime: '3 months', scholarship: true, emoji: '🇮🇪',
  },
  {
    id: 'ucd-smurfit', name: 'UCD Michael Smurfit Graduate Business School', shortName: 'UCD Smurfit',
    category: 'Study Abroad', country: 'Ireland', degreeTypes: ['MBA'], city: 'Dublin', state: 'Ireland',
    totalFee: 2800000, avgPackage: 6000000, highestPackage: 13000000,
    minScore: 70, minGpa: 60, minExpYears: 2, maxExpYears: 10,
    ranking: 2, nirf: null,
    testTypes: ['gmat', 'gre'], tags: ['Ireland', 'EU Access', 'Tech Hub'],
    placementTime: '3 months', scholarship: true, emoji: '🇮🇪',
  },

  // ── EXECUTIVE EDUCATION (India) ──────────────────────────────────────
  {
    id: 'iima-exec', name: 'IIM-A Executive MBA', shortName: 'IIM-A PGPX',
    category: 'Executive Education', country: 'India', degreeTypes: ['MBA'], city: 'Ahmedabad', state: 'Gujarat',
    totalFee: 3200000, avgPackage: 4500000, highestPackage: 12000000,
    minScore: 70, minGpa: 60, minExpYears: 5, maxExpYears: 25,
    ranking: 1, nirf: 1,
    testTypes: ['gmat', 'cat'], tags: ['Senior Leaders', 'Global Peers', '1-Year Program'],
    placementTime: '2 months', scholarship: true, emoji: '👔',
  },
  {
    id: 'isb-exec', name: 'ISB Executive Education', shortName: 'ISB Exec',
    category: 'Executive Education', country: 'India', degreeTypes: ['MBA'], city: 'Hyderabad', state: 'Telangana',
    totalFee: 1500000, avgPackage: 4000000, highestPackage: 10000000,
    minScore: 60, minGpa: 58, minExpYears: 7, maxExpYears: 25,
    ranking: 2, nirf: null,
    testTypes: ['gmat'], tags: ['Mid-Senior', 'Flexible Format', 'Global Faculty'],
    placementTime: '2 months', scholarship: false, emoji: '👔',
  },
  {
    id: 'iimb-exec', name: 'IIM-B Executive Program', shortName: 'IIMB EPGP',
    category: 'Executive Education', country: 'India', degreeTypes: ['MBA'], city: 'Bangalore', state: 'Karnataka',
    totalFee: 2800000, avgPackage: 4200000, highestPackage: 10000000,
    minScore: 70, minGpa: 60, minExpYears: 5, maxExpYears: 20,
    ranking: 3, nirf: null,
    testTypes: ['gmat', 'cat'], tags: ['Tech Leaders', 'Senior Professionals', '1-Year'],
    placementTime: '2 months', scholarship: true, emoji: '👔',
  },
  {
    id: 'iimk-exec', name: 'IIM Kozhikode Digital Leaders', shortName: 'IIM-K DLP',
    category: 'Executive Education', country: 'India', degreeTypes: ['MBA'], city: 'Kozhikode', state: 'Kerala',
    totalFee: 800000, avgPackage: 2500000, highestPackage: 6000000,
    minScore: 50, minGpa: 55, minExpYears: 5, maxExpYears: 20,
    ranking: 4, nirf: null,
    testTypes: ['cat', 'gmat'], tags: ['Online + Weekend', 'Affordable', 'Digital Focus'],
    placementTime: '3 months', scholarship: false, emoji: '👔',
  },

  // ── UPSKILLING ───────────────────────────────────────────────────────
  {
    id: 'iitm-online', name: 'IIT Madras Online BS Degree', shortName: 'IIT-M Online',
    category: 'Upskilling', country: 'India', degreeTypes: ['Other'], city: 'Online', state: 'Pan India',
    totalFee: 350000, avgPackage: 1000000, highestPackage: 3000000,
    minScore: 60, minGpa: 55, minExpYears: 0, maxExpYears: 20,
    ranking: 1, nirf: null,
    testTypes: ['jee', 'cat', 'none'], tags: ['IIT Degree', 'Online', 'Flexible', 'Data Science'],
    placementTime: '6 months', scholarship: true, emoji: '💻',
  },
  {
    id: 'upgrad-ds', name: 'upGrad Data Science', shortName: 'upGrad DS',
    category: 'Upskilling', country: 'India', degreeTypes: ['Other'], city: 'Online', state: 'Pan India',
    totalFee: 400000, avgPackage: 1200000, highestPackage: 2500000,
    minScore: 0, minGpa: 45, minExpYears: 0, maxExpYears: 20,
    ranking: 2, nirf: null,
    testTypes: ['none'], tags: ['Online', 'Job Guarantee', 'Data Science', 'AI/ML'],
    placementTime: '3 months', scholarship: true, emoji: '💻',
  },
  {
    id: 'great-learning', name: 'Great Learning AI & ML', shortName: 'GL AI',
    category: 'Upskilling', country: 'India', degreeTypes: ['Other'], city: 'Online', state: 'Pan India',
    totalFee: 300000, avgPackage: 1000000, highestPackage: 2000000,
    minScore: 0, minGpa: 45, minExpYears: 0, maxExpYears: 20,
    ranking: 3, nirf: null,
    testTypes: ['none'], tags: ['Online', 'AI/ML', 'Certifications', 'Mentorship'],
    placementTime: '3 months', scholarship: true, emoji: '💻',
  },
  {
    id: 'coursera-google', name: 'Google Career Certificates', shortName: 'Google Certs',
    category: 'Upskilling', country: 'India', degreeTypes: ['Other'], city: 'Online', state: 'Global',
    totalFee: 15000, avgPackage: 800000, highestPackage: 1800000,
    minScore: 0, minGpa: 0, minExpYears: 0, maxExpYears: 20,
    ranking: 4, nirf: null,
    testTypes: ['none'], tags: ['Affordable', 'Google Backed', 'Quick', 'Job Ready'],
    placementTime: '3 months', scholarship: true, emoji: '💻',
  },
];

export function getCollegesByCategory(category) {
  return COLLEGES.filter(c => c.category === category);
}

/**
 * Filters the curated university list for the "Preferred Universities" combobox.
 * `degreeType` matches against each entry's `degreeTypes[]` (MBA/MS/MTech/BTech/BBA/Other),
 * which is a finer-grained split than the legacy `category` field above.
 * Returns [] gracefully when country/degreeType aren't selected yet or match nothing.
 */
export function getUniversitiesByCountryAndCategory(country, degreeType) {
  if (!country || !degreeType) return [];
  return COLLEGES.filter(c => c.country === country && c.degreeTypes.includes(degreeType));
}

export function formatFee(rupees) {
  if (rupees >= 10000000) return `₹${(rupees / 10000000).toFixed(1)}Cr`;
  if (rupees >= 100000) return `₹${(rupees / 100000).toFixed(0)}L`;
  if (rupees >= 1000) return `₹${(rupees / 1000).toFixed(0)}K`;
  return `₹${rupees}`;
}

export function formatPackage(rupees) {
  if (rupees >= 10000000) return `₹${(rupees / 10000000).toFixed(1)}Cr LPA`;
  if (rupees >= 100000) return `₹${(rupees / 100000).toFixed(0)} LPA`;
  return `₹${rupees} PA`;
}
